### PR TITLE
JSON-RPC 2.0 Parameter Structures

### PR DESCRIPTION
**Pull request by avfonarev**
According to [JSON-RPC 2.0 Specification](http://www.jsonrpc.org/specification) (4.2 Parameter Structures), one can use _by-name_ parameters. This is something pretty common. Changed a few lines to support this. Also fixed a typo in README.md.

### CODE REVIEW

**Comment by wiistriker** [comment]
thanks

**Comment by dermdaly** [comment]
Any chance you could bump the podspec to 0.3.1 ?  I happen to have a project which needs this change.

**Comment by wiistriker** [comment]
ping @mattt ^^^

**Comment by mattt** [comment]
@wiistriker You're welcome to create releases yourself. Are you familiar with the process? In case you aren't:
1. Update the repository podspec file, bumping the release and tag (which you'll create after you commit this)
2. Tag the commit with the podspec update to the tag
3. `$ git push origin master && git push --tags`
4. If you have push access on @CocoaPods/Specs, create the new spec. Otherwise, fork and create a pull request for the new one.

**Comment by wiistriker** [comment]
@mattt thank you very much. I will try, Never work with CocoaPods. Does it work only with tags? No way to upload master version of library?

**Comment by dermdaly** [comment]
I'm happy to handle this you guys like.

**Comment by mattt** [comment]
@wiistriker Like any software used in production, it's useful to tag semantically-versioned releases. With CocoaPods, you can point to either a tag or an individual commit, but pointing to a tag is much-preferred.

**Comment by wiistriker** [comment]
@mattt https://github.com/CocoaPods/Specs/pull/1192 please, check my PR. Everything is good?

**Comment by mattt** [comment]
Everything looks good. Glad to see it merged in :)

**Pull request merged**
