### PR TITLE
AFJSONRPCProxy implements jsonrpc-NSProxy

### PR DESCRIPTION
**Pull request by boecko**
Hi,

this is the first implementation for my own feature-request https://github.com/AFNetworking/AFJSONRPCClient/issues/2 ;)
No subclassing needed!

Usage:

``` objective-c

#import "AFJSONRPCProxy.h"
...
@protocol MyJSONRPCProtocol
- (void)sum:(NSArray *)numbers
            success:(afproxy_success_callback_t) success
            failure:(afproxy_failure_callback_t) failure;
@end
...
id<MyJSONRPCProtocol> proxy = [AFJSONRPCProxy proxyWithEndpointURL:[NSURL URLWithString:@"http://path.to/json-rpc/service/"] 
                                              protocol:@protocol(MyJSONRPCProtocol)];

[proxy sum:@[@(1), @(2)]
    success:^(NSNumber *sum) {
    // ...
}   failure:^(NSError *error) {
    // ...
}];
```

### CODE REVIEW

**Comment by mattt** [comment]
Thanks for the pull request, @boecko. However, I'm not entirely sure what advantage a proxy implementation would have over subclassing. If this is indeed for interacting with a JSON-RPC webservice, wouldn't the superclass be necessary anyway to actually make the network requests?

`AFJSONRPCClient`, like `AFHTTPClient`, is designed for subclassing. A singleton instance in an application is used to store app state like credentials. A common pattern is for models to implement class methods that return constructed instances by wrapping networking calls to the shared singleton (see the [AFNetworking example project](https://github.com/AFNetworking/AFNetworking/tree/master/Example)). I definitely prefer the clarity of this pattern over proxying, but I'd like to understand more about where you're going with all of this.

**Comment by mattt** [comment]
Ah, now I see what you're getting at. That's clever, but wouldn't it be easier to make the proxy part of the client rather than the other way around to enable dynamic method dispatch? That way you could have:

``` objective-c
[[client proxy] sum:@[@(1), @(2)]
               success:^{...}
               failure:^{...}];
```

Or maybe there's a way to do this nicely with runtime hacks when the client adopt a protocol?

Either way, at this point, it's merely syntactic sugar, but I'm not sure if it's particularly useful or nicer to work with.

**Comment by boecko** [comment]
No .. it wouldn't, because the AFJSONRPCClient does it's job good how it's designed.
A [client proxy] Method would implicate, that  you must pass a @protocol to the client-intializer:

``` objective-c
AFJSONRPCClient *client =
  [AFJSONRPCClient clientWithEndpointURL:[NSURL URLWithString:@"http://path.to/json-rpc/service/"] protocol:@protocol(..)];
```

as it doesn't work without @protocol. The proxy-Method must know how the NSProxy-Object is created.
see - (BOOL)respondsToSelector:(SEL)aSelector

I agree with your intention, this would be better

``` objective-c
id<MyJSONRPCProtocol> proxy = [client proxyWithProtocol:@protocol(MyJSONRPCProtocol)];
```

BTW, that's not just syntatice sugar. 
- The whole purpose of NSProxy is to represent a remote object.
- it eliminates the need for duplicate code for each method
- it's easier to test via Mock-Objects which implement the Protocol
- it's a common pattern in other languages to, see http://code.google.com/p/jsonrpc4j/#Client

``` java

JsonRpcHttpClient client = new JsonRpcHttpClient(
    new URL("http://example.com/UserService.json"));

UserService userService = ProxyUtil.createClientProxy(
    getClass().getClassLoader(),
    UserService.class,
    client);
```

**Comment by mattt** [comment]
`id<MyJSONRPCProtocol> proxy = [client proxyWithProtocol:@protocol(MyJSONRPCProtocol)];`

Yep, that's what I was getting at. 

The proxy class doesn't need to be exposed publicly, though, since the only useful bits would be the `@protocol` methods. Put that in the original `.m`, and we're in business.

**Comment by boecko** [comment]
I would prefer a -private header file for the proxy.m and exclude that one in the pod spec .

Ok?

**Comment by mattt** [comment]
Again, I don't understand the point of a private `.h` file if it's just an implementation detail of the original client. AFNetworking uses private classes in `.m` files all over the place. Excluding it in the podspec would break the functionality.

**Comment by boecko** [comment]
bump

**Comment by mattt** [comment]
Thanks for making those changes. Everything is merged in and tagged with 0.4.0. Cheers!

**Comment by boecko** [comment]
thanks ... but somehow you didn't actually merge my request.
- My commit message is now "Tabs -> Spaces".
- _DANGER, WILL ROBINSON_ - you've got a merge conflict in  AFJSONRPCClient/AFJSONRPCClient.h
  see https://github.com/AFNetworking/AFJSONRPCClient/blob/master/AFJSONRPCClient/AFJSONRPCClient.h#L84

**Pull request closed without merging**
